- name: Hello World by me
  # You may pin to the exact commit or the version.
  # uses: lgmorand/github-action-hello@57e7ea2aeb40a83c584aea670a62e2a6304a29db
  uses: lgmorand/github-action-hello@v2.0.0
  with:
    # firstname of the person
    firstname: Jerry
    # firstname of the person
    # firstname2: # default is Jane
