--- #start document
name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "14"
      - run: npm install -g bats
      - run: bats -v

      - name: Hello World by me
        uses: lgmorand/github-action-hello@v2.0.0
        with:
          firstname: Jerry
      - name: Test Javascript Hello Action
        uses: adeloyedeji/github-actions-hello@v1.0
        with:
          who-to-greet: Mineko
... #end document
